### ISSUE TITLE
unable to quit app by clicking on exit after preset change from configuration

### ISSUE THREAD

**Issue by anjannath** [crc-org/tray-electron#196]
### Logs
```
[2] Files successfully emitted, waiting for typecheck results...
[2] Issues checking in progress...
[2] No issues found.
[1] Status tick: HTTPError: Response code 500 (Internal Server Error)
[1] Status tick: HTTPError: Response code 500 (Internal Server Error)
[1] Failed to set config
[1] Status tick: HTTPError: Response code 500 (Internal Server Error)
[1] Status tick: HTTPError: Response code 500 (Internal Server Error)
[1] (node:28855) UnhandledPromiseRejectionWarning: HTTPError: Response code 500 (Internal Server Error)
[1]     at EventEmitter.<anonymous> (/Users/anjan/github.com/code-ready/tray-electron/node_modules/got/source/as-promise.js:74:19)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1] (Use `Electron --trace-warnings ...` to show where the warning was created)
[1] (node:28855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[1] Status tick: HTTPError: Response code 500 (Internal Server Error)
[1] Status tick: HTTPError: Response code 500 (Internal Server Error)
[1] Status tick: HTTPError: Response code 500 (Internal Server Error)
[1] Status tick: HTTPError: Response code 500 (Internal Server Error)
[1] Status tick: HTTPError: Response code 500 (Internal Server Error)
[1] Logs tick: TypeError: Object has been destroyed
[1] Logs tick: TypeError: Object has been destroyed
[1] Status tick: HTTPError: Response code 500 (Internal Server Error)
[1] (node:28855) UnhandledPromiseRejectionWarning: TypeError: Object has been destroyed
[1]     at pollStatus (/Users/anjan/github.com/code-ready/tray-electron/build/src/main.js:336:98)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1] (node:28855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[1] Logs tick: TypeError: Object has been destroyed
[1] Logs tick: TypeError: Object has been destroyed
[1] Logs tick: TypeError: Object has been destroyed
[1] Logs tick: TypeError: Object has been destroyed
^C[1] /Users/anjan/github.com/code-ready/tray-electron/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGINT
[0] npm run watch exited with code SIGINT
[2] cd frontend && npm start exited with code SIGINT
[1] electron . exited with code 1
```

- some objects got destroyed
- there's an unhandled exception

**Comment by anjannath** [comment]
resolved via #201
